AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: clients-microservice

Parameters:
  UserPoolId:
    Type: String
    Description: User Pool ID for cognito provider
  UserPoolClientId:
    Type: String
    Description: Client ID for user pool

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 100
    MemorySize: 128
    Architectures:
      - x86_64
    Environment:
      Variables:
        DSQL_CLUSTER_URL: ""
        REGION: !Ref "AWS::Region"
        userId: ""

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: GeneralAuth
        Authorizers:
          GeneralAuth:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              audience:
                - !Ref UserPoolClientId
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPoolId}
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - OPTIONS
          - PATCH
          - DELETE
        AllowOrigins:
          - http://localhost:3001
          - https://yakhousam-invoicing-app.netlify.app
          - https://invoicing-app.khoudiryaya.dev
        AllowHeaders:
          - Content-Type
          - Authorization

  postClientFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodejs
      Handler: postClient.handler

      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
            ApiId: !Ref HttpApi

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - functions/postClient.ts

  getAllClientsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodejs
      Handler: getAllClients.handler
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            ApiId: !Ref HttpApi

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - functions/getAllClients.ts

  getClientByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodejs
      Handler: getClientById.handler
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /{clientId}
            Method: GET
            ApiId: !Ref HttpApi

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - functions/getClientById.ts

  updateClientFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodejs
      Handler: updateClient.handler

      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /{clientId}
            Method: PATCH
            ApiId: !Ref HttpApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - functions/updateClient.ts

Outputs:
  HttpApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/
